#!/bin/bash
sudo yum update -y
sudo amazon-linux-extras install epel php7.4 -y
sudo yum install -y httpd.x86_64 ruby wget aws-cfn-bootstrap
curl https://aws-codedeploy-eu-west-1.s3.amazonaws.com/latest/install -o install
chmod +x ./install
sudo ./install auto
sudo systemctl enable codedeploy-agent
sudo systemctl start codedeploy-agent
sudo systemctl restart codedeploy-agent
sudo yum clean metadata
sudo yum install -y php-common php-json php-pdo php-gd php-cli php-xml php-fpm php-mysqlnd php-process mysql mysql-server mysql-devel mysql-libs -y
sudo test -d /opt/aws/bin/ && export PATH=$PATH:/opt/aws/bin/
